Fix constructors generation for subclasses
Subclasses should generate constructor as static methods
since we don't want to chain C# constructors in the GObject
creation.

Also remove the name_constructors hack no longer needed

TestFundamentalSubObject.cs(56,10): error CS1729: 'TestFundamentalObject' does not contain a constructor that takes 0 arguments
TestFundamentalSubObjectNoGetSetFunc.cs(30,10): error CS1729: 'TestFundamentalObjectNoGetSetFunc' does not contain a constructor that takes 0 arguments